In [1]:
import pandas as pd
import os
from random import randint
import random 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data_dict = {
    'General': [
        'Brain Injury Screening Questionnaire (BISQ)',
        'Child/Adult Satisfaction Questionnaire',
        'Consent',
        'Demographic Questionnaire',
        'Demographics Supplement',
        'Family History Questionnaire – Parent',
        'Hollingshead Four-Factor Index of Socioeconomic Status (SES)',
        'Medical History Questionnaire – Child',
        'Medications/Medical Conditions – Parent'
    ],
    'Physical': [
        '6-Minute Bike Test',
        'Actigraphy',
        'Blood Draw',
        'Cambridge-Hopkins Restless Legs Syndrome (CHRLS, 18+)',
        'Color Vision',
        'Edinburgh Handedness Questionnaire (EHQ, 6–17)',
        'Grip Strength',
        'Grooved Pegboard',
        'International Physical Activity Questionnaire (IPAQ, 15+)',
        'Pittsburgh Sleep Quality Index (PSQI, 13+)',
        'Tanner Scale',
        'Weight/Height, Vital Signs, Hip/Waist Measurement'
    ],
    'Diagnostic': [
        'Kiddie Schedule for Affective Disorders and Schizophrenia, Present and Lifetime Version (KSADS-PL, 6–17)',
        'Structured Clinical Interview for DSM Disorders (SCID, 18+)',
        'Children’s Yale-Brown Obsessive Compulsive Scale (CY-BOCS, 6–17)',
        'Vineland Adaptive Behavior Scales (VABS, 6–17)',
        'Yale Global Tic Severity Scale (YGTSS, 6–17)'
    ],
    'Cognitive': [
        'Attention Network Test (ANT)',
        'Delis-Kaplan Executive Function System (D-KEFS) – Verbal Fluency (8+)',
        'DKEFS – Trails (8+)',
        'DKEFS – Design Fluency (8+)',
        'DKEFS – Color-Word Interference Test (8+)',
        'DKEFS – Tower (8+)',
        'Digit Span',
        'Penn Computerized Neurocognitive Battery (CNB)',
        'Rey Auditory Verbal Learning Test (RAVLT; 8+)',
        'Wechsler Abbreviated Scale of Intelligence-II (WASI)',
        'Wechsler Individual Achievement Test-II (WIAT)'
    ],
    'Imaging': [
        'Magnetic Resonance Imaging (MRI) Session',
        'Mock Scan',
        'MRI-Questionnaire (MRIQ; 13+)'
    ],
    'Substance Use and Addiction Measures': [
        'Urine Drug Test (11+)',
        'Comprehensive Addiction Severity Index for Adolescents (CASI, 11+)',
        'Fagerstrom Test for Nicotine Dependence (FTND, 18+)',
        'Modified Fagerstrom Tolerance Questionnaire – Adolescents (FTQA, 13–17)',
        'National Institute on Drug Abuse Questionnaire (NIDA, 11+)'
    ],
    'Behavioral Tasks': [
        'Behavioral Indicator of Resiliency to Distress (BIRD)',
        'Dot Probe'
    ],
    'Behavior and Phenotypic Characterization Questionnaires': [
        'The High-Functioning Autism Spectrum Screening Questionnaire (ASSQ, 6–17)',
        'Adult Self-Report (ASR, 18+)',
        'Adult Temperament Questionnaire (ATQ, 16+)',
        'Behavior Assessment System for Children 2nd Edition – Parent Rating Scale (BASC, 7–17)',
        'Beck Depression Inventory (BDI, 18+)',
        'Child Behavior Checklist (CBCL, 7–17)',
        'CBCL-Adaptive Functioning (7–17)',
        'Children’s Behavior Questionnaire Very Short Form (CBQ-VSF, 6–8)',
        'Children’s Depression Inventory 2 (CDI-2, 11–17)',
        'Child Eating Behavior Questionnaire (CEBQ, 7–11)',
        'Cognitive Failures Questionnaire (CFQ, 16+)',
        'Connors 3rd Edition – Parent Short Form (6–17)',
        'Connors 3rd Edition – Self-Report Short Form (8–17)',
        'Early Adolescent Temperament Questionnaire (EATQ, 9–15)',
        'Eating Disorder Examination Questionnaire (EDEQ, 13+)',
        'Inventory of Callous-Unemotional Traits – Parent Version (ICU-P, 7–17)',
        'Inventory of Callous-Unemotional Traits – Youth Self Report (ICU-Y, 13+)',
        'Interpersonal Reactivity Index (IRI, 13+)',
        'Multidimensional Anxiety Scale for Children (MASC, 8–17)',
        'NEO Five Factor Inventory - 3 (NEO, 12–17)',
        'The 21-Item Peters et al. Delusions Inventory (PDI, 13+)',
        'Phenotyping and eXposures (PhenX) Sex History Questionnaire (13+)',
        'Repetitive Behaviors Scale – Revised (RBS-R, 6–17)',
        'Sex Role Identity Scale (13+)',
        'Sexual Orientation Scale (13+)',
        'Social Responsiveness Scale-Parent Report (SRS, 7–17)',
        'State-Trait Anxiety Inventory (STAI, 18+)',
        'Strengths and Weaknesses of Attention-Deficit/Hyperactivity Disorder Symptoms and Normal Behavior Scale (SWAN, 6–17)',
        'Three-Factor Eating Questionnaire (TFEQ, 12+)',
        'Trauma Symptom Checklist for Children (TSC-C, 11–17)',
        'Trauma Symptoms Checklist for Adults (TSC-40, 18+)',
        'University of California at Los Angeles Posttraumatic Stress Disorder Reaction Index (UCLA-PTSD) Parent (6–17)',
        'UCLA-PTSD Child (8–17)',
        'UPPS-P Impulsive Behavior Scale (18+)',
        'Youth Self-Report (YSR, 11–17)',
        'YSR Adaptive Functioning (11–17)',
        'Youth Risk Behavior Surveillance System Middle School/High School (YSRBS, 12+)'
    ]
}

In [16]:
for cat, test_list in data_dict.items():
    for ind, test in enumerate(test_list):
        if '(' in test:
            start, end = test.index('('), test.index(')')
            if start + 1 < len(test) and not test[start + 1].isdigit():
                test_list[ind] = test[start+1:end].split()[0].split(',')[0].replace(';', '')

In [18]:
data_list = []
for cat, test_list in data_dict.items():
    data_list.append(f'**{cat}**')
    for test in test_list:
        data_list.append(test)

In [21]:
df = pd.DataFrame({'Assessments/Procedures': data_list})
df.to_csv('/Users/danielgarcia-barnett/Desktop/ALG_data/ALG_data.csv', index=False)

In [22]:
df = pd.read_csv('/Users/danielgarcia-barnett/Desktop/ALG_data/table_1_v2.csv', keep_default_na=False)

In [26]:
data_list

['**General**',
 'BISQ',
 'Child/Adult Satisfaction Questionnaire',
 'Consent',
 'Demographic Questionnaire',
 'Demographics Supplement',
 'Family History Questionnaire – Parent',
 'SES',
 'Medical History Questionnaire – Child',
 'Medications/Medical Conditions – Parent',
 '**Physical**',
 '6-Minute Bike Test',
 'Actigraphy',
 'Blood Draw',
 'CHRLS',
 'Color Vision',
 'EHQ',
 'Grip Strength',
 'Grooved Pegboard',
 'IPAQ',
 'PSQI',
 'Tanner Scale',
 'Weight/Height, Vital Signs, Hip/Waist Measurement',
 '**Diagnostic**',
 'KSADS-PL',
 'SCID',
 'CY-BOCS',
 'VABS',
 'YGTSS',
 '**Cognitive**',
 'ANT',
 'D-KEFS',
 'DKEFS – Trails (8+)',
 'DKEFS – Design Fluency (8+)',
 'DKEFS – Color-Word Interference Test (8+)',
 'DKEFS – Tower (8+)',
 'Digit Span',
 'CNB',
 'RAVLT',
 'WASI',
 'WIAT',
 '**Imaging**',
 'MRI',
 'Mock Scan',
 'MRIQ',
 '**Substance Use and Addiction Measures**',
 'Urine Drug Test (11+)',
 'CASI',
 'FTND',
 'FTQA',
 'NIDA',
 '**Behavioral Tasks**',
 'BIRD',
 'Dot Probe',
 '**Behavior and Phenotypic Characterization Questionnaires**',
 'ASSQ',
 'ASR',
 'ATQ',
 'BASC',
 'BDI',
 'CBCL',
 'CBCL-Adaptive Functioning (7–17)',
 'CBQ-VSF',
 'CDI-2',
 'CEBQ',
 'CFQ',
 'Connors 3rd Edition – Parent Short Form (6–17)',
 'Connors 3rd Edition – Self-Report Short Form (8–17)',
 'EATQ',
 'EDEQ',
 'ICU-P',
 'ICU-Y',
 'IRI',
 'MASC',
 'NEO',
 'PDI',
 'PhenX',
 'RBS-R',
 'Sex Role Identity Scale (13+)',
 'Sexual Orientation Scale (13+)',
 'SRS',
 'STAI',
 'SWAN',
 'TFEQ',
 'TSC-C',
 'TSC-40',
 'UCLA-PTSD',
 'UCLA-PTSD Child (8–17)',
 'UPPS-P Impulsive Behavior Scale (18+)',
 'YSR',
 'YSR Adaptive Functioning (11–17)',
 'YSRBS']

In [25]:
for test in data_list:
    if test in df['Assessments by Visit'].values:
        print(test)

Consent
Demographic Questionnaire
Demographics Supplement
6-Minute Bike Test
Blood Draw
Color Vision
Grip Strength
Grooved Pegboard
Weight/Height, Vital Signs, Hip/Waist Measurement
Digit Span
MRI
Urine Drug Test (11+)

In [35]:
def get_sched(fpath):
    with open(fpath, 'r') as f:
        lines = f.readlines()
        lines = [line.split() for line in lines]
    schedule = pd.DataFrame(lines, columns=['time', 'stim_code', 'duration', '?', 'stim_type'])
    schedule = schedule.apply(pd.to_numeric, errors='ignore')
    return schedule
def save_sched(df, fpath):
    df.to_csv(fpath, sep=' ', header=False, index=False)

In [40]:
fpath = '/Users/danielgarcia-barnett/Desktop/prog_choice_reaction_time/Stimuli/Schedules/4_options/schedule-001.par'
get_sched(fpath)

/var/folders/w0/4d261sg51qjdphncfst0x4fr0000gn/T/ipykernel_71347/1754735922.py:6: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  schedule = schedule.apply(pd.to_numeric, errors='ignore')

     time  stim_code  duration    ? stim_type
0     0.0          0       1.0  1.0      NULL
1     1.0          2       2.0  1.0    square
2     3.0          0       1.0  1.0      NULL
3     4.0          3       2.0  1.0    circle
4     6.0          0       1.9  1.0      NULL
..    ...        ...       ...  ...       ...
76  123.1          0       1.2  1.0      NULL
77  124.3          1       2.0  1.0      line
78  126.3          0       1.1  1.0      NULL
79  127.4          2       2.0  1.0    square
80  129.4          0       1.6  1.0      NULL

[81 rows x 5 columns]

In [39]:
for dirs, fldrs, files in os.walk('/Users/danielgarcia-barnett/Desktop/prog_choice_reaction_time/Stimuli/Schedules'):
    for file in files:
        if file.endswith('.par'):
            fpath = os.path.join(dirs, file)
            df = get_sched(fpath)
            df = pd.concat([df.iloc[41:42], df]).reset_index(drop=True)
            time = [0]+[float(df.loc[0:i, 'duration'].sum()) for i in range(len(df))]
            df['time'] = time[:-1]
            save_sched(df, fpath)

/var/folders/w0/4d261sg51qjdphncfst0x4fr0000gn/T/ipykernel_71347/1754735922.py:6: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  schedule = schedule.apply(pd.to_numeric, errors='ignore')

In [6]:
dirs = '/Users/danielgarcia-barnett/Desktop/prog_choice_reaction_time/Stimuli/Schedules/practice'
stim_list = ['line', 'square', 'circle', 'triangle']*2
for i in range(100):
    random.shuffle(stim_list)
    duration = [np.round(random.uniform(1, 2), 1) for i in range(8)]
    null_data = pd.DataFrame({'duration':duration, 'stim_type':['NULL']*8}).reset_index(drop=True)
    stim_data = pd.DataFrame({'duration':[2]*8, 'stim_type':stim_list}).reset_index(drop=True)
    practice_data = pd.concat([stim_data, null_data], keys=[0,1]).sort_index(level=1).reset_index(drop=True)
    practice_data.to_csv(os.path.join(dirs, f'schedule-{i:03}.csv'))

In [11]:
practice_data

    duration stim_type
0        2.0    square
1        1.8      NULL
2        2.0  triangle
3        1.5      NULL
4        2.0    circle
5        1.8      NULL
6        2.0    circle
7        1.7      NULL
8        2.0    circle
9        1.4      NULL
10       2.0    square
11       1.6      NULL
12       2.0    square
13       1.2      NULL
14       2.0  triangle
15       1.3      NULL
16       2.0  triangle
17       1.1      NULL
18       2.0    circle
19       1.7      NULL
20       2.0      line
21       1.8      NULL
22       2.0      line
23       1.6      NULL
24       2.0    square
25       1.3      NULL
26       2.0  triangle
27       1.4      NULL
28       2.0  triangle
29       1.7      NULL
30       2.0      line
31       1.5      NULL
32       2.0    circle
33       1.4      NULL
34       2.0      line
35       1.5      NULL
36       2.0    square
37       2.0      NULL
38       2.0      line
39       1.1      NULL

In [80]:
df[::-1]

      time  stim_code  duration    ? stim_type
239  419.0          0       1.0  1.0      NULL
238  417.0          1       2.0  1.0      line
237  416.5          0       0.5  1.0      NULL
236  414.5          2       2.0  1.0    square
235  412.5          0       2.0  1.0      NULL
..     ...        ...       ...  ...       ...
4      5.0          4       2.0  1.0    circle
3      4.5          0       0.5  1.0      NULL
2      2.5          1       2.0  1.0      line
1      2.0          0       0.5  1.0      NULL
0      0.0          2       2.0  1.0    square

[240 rows x 5 columns]

# Generating the Order Text Files

In [4]:
order_dirs = '/Users/AP-CNL/Desktop/4RT/Stimuli/Order'

In [8]:
opt_dict = {'1_option':['line'],
            '2_options':['line', 'square'],
            '4_options':['line', 'circle', 'triangle', 'square']}

In [40]:
def get_order(opt_list):
    count = 40 // len(opt_list)
    count_list = [count for i in range(len(opt_list))]
    order_list = []
    i = 40
    while i > 0:
        index = randint(0, len(opt_list)-1)
        if count_list[index] > 0:
            count_list[index] = count_list[index] - 1
            order_list.append(opt_list[index])
            i -= 1
        else:
            continue
    return order_list

In [45]:
for fldr in os.listdir(order_dirs):
    for i in range(1, 101):
        opt_list = get_order(opt_dict[fldr])
        txt_path = os.path.join(order_dirs, fldr, f'order_{i:03}.txt')
        with open(txt_path, 'w') as file:
            file.writelines(f'{opt}/n' for opt in opt_list)

# Other Testing

In [7]:
one_opt_list = os.listdir('/Users/AP-CNL/Desktop/4RT/Stimuli/Order/1_option')
random.shuffle(one_opt_list)
one_opt_list[0]

'order_036.txt'

In [17]:
txt_path = '/Users/AP-CNL/Desktop/4RT/Stimuli/Order/4_options/order_001.txt'
with open(txt_path, 'r') as file:
    order_list = [line.strip() for line in file]

order_list = [item for pair in zip(order_list, ['feedback']*len(order_list)) for item in pair][:-1]
print(order_list)

['circle', 'feedback', 'line', 'feedback', 'triangle', 'feedback', 'square', 'feedback', 'line', 'feedback', 'circle', 'feedback', 'circle', 'feedback', 'square', 'feedback', 'circle', 'feedback', 'line', 'feedback', 'square', 'feedback', 'circle', 'feedback', 'square', 'feedback', 'square', 'feedback', 'line', 'feedback', 'triangle', 'feedback', 'triangle', 'feedback', 'line', 'feedback', 'square', 'feedback', 'triangle', 'feedback', 'line', 'feedback', 'triangle', 'feedback', 'triangle', 'feedback', 'triangle', 'feedback', 'triangle', 'feedback', 'line', 'feedback', 'line', 'feedback', 'square', 'feedback', 'square', 'feedback', 'circle', 'feedback', 'square', 'feedback', 'square', 'feedback', 'triangle', 'feedback', 'line', 'feedback', 'triangle', 'feedback', 'line', 'feedback', 'circle', 'feedback', 'circle', 'feedback', 'circle', 'feedback', 'circle']